---
- name: restart weaviate
  systemd:
    name: weaviate
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: ansible_service_mgr == 'systemd'

- name: reload systemd
  systemd:
    daemon_reload: yes
  when: ansible_service_mgr == 'systemd'
