#!/bin/bash
# Manual step-by-step rescue commands
# Run these one by one if the automatic script fails

echo "=== MANUAL RESCUE STEPS ==="
echo ""
echo "1. First, check what storage devices are available:"
echo "   lsblk"
echo ""
echo "2. Check RAID status:"
echo "   cat /proc/mdstat"
echo ""
echo "3. Try to assemble RAID (if you have RAID):"
echo "   mdadm --assemble --scan"
echo "   OR manually: mdadm --assemble /dev/md0 /dev/sda1 /dev/sdb1"
echo ""
echo "4. Identify your root partition (look for largest partition):"
echo "   lsblk"
echo "   Common locations: /dev/md0p1, /dev/md0, /dev/sda1, /dev/nvme0n1p1"
echo ""
echo "5. Mount your root partition (replace with your actual partition):"
echo "   mkdir -p /mnt/serverdisk"
echo "   mount /dev/md0p1 /mnt/serverdisk"
echo ""
echo "6. Check if mount was successful:"
echo "   ls /mnt/serverdisk"
echo "   # You should see: bin, boot, etc, home, usr, var, etc."
echo ""
echo "7. Prepare chroot environment:"
echo "   mount --bind /dev /mnt/serverdisk/dev"
echo "   mount --bind /proc /mnt/serverdisk/proc"
echo "   mount --bind /sys /mnt/serverdisk/sys"
echo ""
echo "8. Enter chroot:"
echo "   chroot /mnt/serverdisk /bin/bash"
echo ""
echo "9. Once in chroot, reset UFW:"
echo "   ufw --force reset"
echo "   ufw allow 22/tcp"
echo "   ufw default deny incoming"
echo "   ufw default allow outgoing"
echo "   ufw --force enable"
echo ""
echo "10. Fix SSH config:"
echo "    sed -i 's/^Port .*/Port 22/' /etc/ssh/sshd_config"
echo "    sed -i 's/^#Port 22/Port 22/' /etc/ssh/sshd_config"
echo "    sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config"
echo ""
echo "11. Disable fail2ban:"
echo "    systemctl stop fail2ban"
echo "    systemctl disable fail2ban"
echo "    fail2ban-client unban --all"
echo ""
echo "12. Clear iptables:"
echo "    iptables -F"
echo "    iptables -X"
echo "    iptables -P INPUT ACCEPT"
echo ""
echo "13. Create emergency user:"
echo "    useradd -m -s /bin/bash emergency"
echo "    echo 'emergency:emergency123' | chpasswd"
echo "    usermod -aG sudo emergency"
echo ""
echo "14. Exit chroot:"
echo "    exit"
echo ""
echo "15. Unmount:"
echo "    umount /mnt/serverdisk/sys"
echo "    umount /mnt/serverdisk/proc"
echo "    umount /mnt/serverdisk/dev"
echo "    umount /mnt/serverdisk"
echo ""
echo "16. Reboot into normal mode from Hetzner console"
echo ""
echo "=== END MANUAL STEPS ==="
