global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Container metrics via cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Node metrics via Node Exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Application metrics
  - job_name: 'application'
    static_configs:
      - targets: ['app:8000']  # Adjust port based on your application

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']
