name: Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Ansible and linters
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint

      - name: Lint Ansible Playbooks
        run: |
          ansible-lint ansible/*.yml ansible/roles/*/tasks/*.yml ansible/roles/*/handlers/*.yml

      - name: Lint YAML Files
        run: |
          yamllint ansible/*.yml ansible/roles/*/tasks/*.yml ansible/roles/*/handlers/*.yml ansible/roles/*/defaults/*.yml ansible/roles/*/vars/*.yml ansible/roles/*/meta/*.yml ansible/roles/*/files/*.yml ansible/roles/*/templates/*.yml

  format:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install yq
        run: |
          pip install yq

      - name: Format YAML Files
        run: |
          yq eval-all -i '... style="block"' ansible/*.yml ansible/roles/*/tasks/*.yml ansible/roles/*/handlers/*.yml ansible/roles/*/defaults/*.yml ansible/roles/*/vars/*.yml ansible/roles/*/meta/*.yml ansible/roles/*/files/*.yml ansible/roles/*/templates/*.yml