services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./supabase/db-data:/var/lib/postgresql/data
    networks:
      - public_proxy

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    restart: unless-stopped
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres?sslmode=disable
    networks:
      - public_proxy

  kong:
    image: supabase/kong:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=db
      - KONG_PG_PASSWORD=${POSTGRES_PASSWORD}
      - KONG_PLUGINS=prometheus
      - KONG_STATUS_LISTEN=0.0.0.0:8100
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8100:8100"
    networks:
      - public_proxy

  studio:
    image: supabase/studio:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - public_proxy

  postgrest:
    image: supabase/postgrest:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - public_proxy

  gotrue:
    image: supabase/gotrue:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - public_proxy

  storage:
    image: supabase/storage-api:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - public_proxy

  realtime:
    image: supabase/realtime:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - public_proxy

  vector:
    image: supabase/vector:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - public_proxy

  # Optional extras (left enabled here; set to false in your Ansible role if you want them removed):
  logflare:
    image: supabase/logflare:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - public_proxy

  imgproxy:
    image: supabase/imgproxy:latest
    restart: unless-stopped
    networks:
      - public_proxy

  pg-meta:
    image: supabase/pg-meta:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - public_proxy

  edge-runtime:
    image: supabase/edge-runtime:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - public_proxy

  migration-service:
    image: supabase/migration-tool:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - public_proxy

networks:
  public_proxy:
    external: true
