---
# RabbitMQ Test Playbook
# This playbook tests the RabbitMQ role with a basic configuration

- name: Test RabbitMQ Installation
  hosts: rabbitmq_servers
  become: true
  vars:
    rabbitmq_users:
      - user: admin
        password: "{{ vault_rabbitmq_admin_password | default('adminpass') }}"
        vhost: /
        configure_priv: '.*'
        write_priv: '.*'
        read_priv: '.*'
        tags: administrator
      - user: monitoring
        password: "{{ vault_rabbitmq_monitoring_password | default('monitorpass') }}"
        vhost: /
        configure_priv: ''
        write_priv: ''
        read_priv: '.*'
        tags: monitoring
    
    rabbitmq_vhosts:
      - /
      - /ai
      - /monitoring
    
    rabbitmq_policies:
      - name: ha-policy
        vhost: /
        pattern: '^ha\..*'
        definition:
          ha-mode: all
          ha-sync-mode: automatic
        priority: 0
        apply-to: all
  
  roles:
    - role: rabbitmq
      tags: [rabbitmq, messaging]
  
  post_tasks:
    - name: Verify RabbitMQ service is running
      ansible.builtin.systemd:
        name: rabbitmq-server
        state: started
        enabled: yes
      register: rabbitmq_service
      failed_when: false
    
    - name: Verify RabbitMQ management interface
      ansible.builtin.uri:
        url: "http://{{ ansible_host }}:15672/api/overview"
        method: GET
        user: admin
        password: "{{ vault_rabbitmq_admin_password | default('adminpass') }}"
        force_basic_auth: yes
        status_code: 200
        timeout: 10
      register: rabbitmq_api
      until: rabbitmq_api.status == 200
      retries: 5
      delay: 5
      ignore_errors: yes
    
    - name: Display RabbitMQ status
      ansible.builtin.debug:
        msg: "RabbitMQ is running and accessible"
      when: rabbitmq_api.status == 200
    
    - name: Display RabbitMQ connection details
      ansible.builtin.debug:
        msg: |
          RabbitMQ Management: http://{{ ansible_host }}:15672
          AMQP Port: 5672
          Prometheus Metrics: http://{{ ansible_host }}:15692/metrics
      when: rabbitmq_api.status == 200

- name: Measure RabbitMQ message processing time
  hosts: rabbitmq
  become: yes
  tasks:
    - name: Install Apache Benchmark (ab) for testing
      apt:
        name: apache2-utils
        state: present

    - name: Generate a large number of messages
      command: |
        for i in {1..10000}; do
          echo "Message $i" | rabbitmqadmin publish routing_key=test_queue payload="Message $i"
        done
      args:
        chdir: /tmp

    - name: Measure message processing time
      command: ab -n 10000 -c 100 http://localhost:15672/api/queues/%2f/test_queue/get?count=10000&ackmode=ack_requeue_false&encoding=auto&truncate=50000
      register: ab_output

    - name: Display message processing time
      debug:
        msg: "Time taken to process 10000 messages: {{ ab_output.stdout_lines[-1] }}"