---
# Cloudflare credentials
cloudflare_email: "{{ vault_cloudflare_email }}"
cloudflare_api_token: "{{ vault_cloudflare_api_token }}"
cloudflare_zone_id: "{{ vault_cloudflare_zone_id }}"

# Database credentials
postgres_password: "{{ vault_postgres_password }}"
neo4j_password: "{{ vault_neo4j_password }}"
clickhouse_password: "{{ vault_clickhouse_password }}"

# Application secrets
langfuse_salt: "{{ vault_langfuse_salt }}"
encryption_key: "{{ vault_encryption_key }}"
nextauth_secret: "{{ vault_nextauth_secret }}"

# OAuth credentials
oauth_client_id: "{{ vault_oauth_client_id }}"
oauth_client_secret: "{{ vault_oauth_client_secret }}"

# Monitoring credentials
grafana_admin_password: "{{ vault_grafana_admin_password }}"

# Flowise credentials
flowise_username: "{{ vault_flowise_username }}"
flowise_password: "{{ vault_flowise_password }}"

# RabbitMQ credentials
rabbitmq_password: "{{ vault_rabbitmq_password }}"
rabbitmq_erlang_cookie: "{{ vault_rabbitmq_erlang_cookie }}"

# SSL certificates (if not using Cloudflare)
ssl_private_key: "{{ vault_ssl_private_key }}"
ssl_certificate: "{{ vault_ssl_certificate }}"

# Weaviate authentication
weaviate_api_key: "{{ vault_weaviate_api_key }}"

# Local AI API keys
local_ai_api_key: "{{ vault_local_ai_api_key }}"
hf_token: "{{ vault_hf_token }}"
