---
# Agentic RAG - Main Tasks
# This role deploys and manages the Agentic RAG service

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags: [install, config]

- name: Install system dependencies
  apt:
    name:
      - python3-pip
      - python3-venv
      - redis-server
    state: present
  become: true

- name: Create service user and group
  user:
    name: "{{ agentic_rag_user }}"
    group: "{{ agentic_rag_group }}"
    system: true
    create_home: false
  become: true

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ agentic_rag_user }}"
    group: "{{ agentic_rag_group }}"
    mode: '0755'
  loop:
    - "{{ agentic_rag_base_dir }}"
    - "{{ agentic_rag_config_dir }}"
    - "{{ agentic_rag_data_dir }}"
    - "{{ agentic_rag_log_dir }}"
  become: true

# Application Setup
- name: Deploy configuration
  template:
    src: config.yml.j2
    dest: "{{ agentic_rag_config_dir }}/config.yml"
    owner: "{{ agentic_rag_user }}"
    group: "{{ agentic_rag_group }}"
    mode: '0644'
  notify: restart agentic-rag

- name: Install Python requirements
  pip:
    name:
      - langchain
      - weaviate-client
      - redis
      - prometheus-client
      - langfuse
    virtualenv: "{{ agentic_rag_base_dir }}/venv"
    state: present
  become: true
  become_user: "{{ agentic_rag_user }}"

# Service Setup
- name: Install systemd service
  template:
    src: agentic-rag.service.j2
    dest: /etc/systemd/system/agentic-rag.service
    mode: '0644'
  notify:
    - reload systemd
    - restart agentic-rag
  become: true

# Integration Setup
- name: Configure Langfuse integration
  template:
    src: langfuse_config.py.j2
    dest: "{{ agentic_rag_config_dir }}/langfuse_config.py"
    owner: "{{ agentic_rag_user }}"
    group: "{{ agentic_rag_group }}"
    mode: '0644'
  when: langfuse_enabled | bool
  notify: restart agentic-rag

# Health Check
- name: Ensure service is running
  systemd:
    name: agentic-rag
    state: started
    enabled: yes
  become: true