---
- name: Install Docker prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    state: present

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Start and enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add deploy user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Install Docker Compose
  pip:
    name: docker-compose
    state: present

- name: Create Docker directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/docker
    - /opt/docker/stacks
    - /opt/docker/volumes
    - /opt/docker/config

- name: Create Docker config directory
  file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: Configure Docker daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'
  notify: restart docker

- name: Configure Docker compose version
  copy:
    content: "{{ docker_compose_version }}"
    dest: /opt/docker/.compose-version
    mode: '0644'

- name: Create Docker network
  block:
    - name: Create Docker network
      docker_network:
        name: "{{ docker_network_name }}"
        driver: bridge
        ipam_config:
          - subnet: "{{ docker_network_subnet }}"
            gateway: "{{ docker_network_gateway }}"
        state: present
  when: docker_network_name is defined
