---
- name: restart neo4j
  systemd:
    name: neo4j
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: ansible_service_mgr == 'systemd'

- name: reload systemd
  systemd:
    daemon_reload: yes
  when: ansible_service_mgr == 'systemd'
